"""
Guardrails for the Medical Diagnosis Bot.

INPUT  guardrail — runs BEFORE the ML model sees any data.
OUTPUT guardrail — runs AFTER the model returns predictions.

These are intentionally simple and conservative: when in doubt,
flag for human review rather than silently proceeding.
"""

from pydantic import BaseModel, Field, model_validator
from typing import Any

# ---------------------------------------------------------------------------
# Diseases that always require a doctor, regardless of confidence
# ---------------------------------------------------------------------------
HIGH_RISK_DISEASES = {
    "pneumonia", "tuberculosis", "meningitis", "sepsis",
    "heart attack", "stroke", "appendicitis", "covid-19", "covid19",
}

DISCLAIMER = (
    "\n\n---\n"
    "**DISCLAIMER**: This report is generated by an AI clinical decision "
    "support tool. It does NOT replace the judgement of a licensed physician. "
    "All outputs must be reviewed by a qualified clinician before any "
    "treatment decision is made."
)


# ---------------------------------------------------------------------------
# Input model — validates symptom flags before inference
# ---------------------------------------------------------------------------

class SymptomInput(BaseModel):
    """
    Validates patient symptom input before it reaches the ML model.
    All symptom fields are binary (0 or 1). At least one must be present.
    """
    symptoms: dict[str, int] = Field(
        ...,
        description="Dict of symptom_name -> 0 or 1"
    )
    age: int | None = Field(default=None, ge=0, le=120)

    @model_validator(mode="after")
    def check_at_least_one_symptom(self) -> "SymptomInput":
        active = [k for k, v in self.symptoms.items() if v == 1]
        if not active:
            raise ValueError("At least one symptom must be present (value=1).")
        return self

    @model_validator(mode="after")
    def check_binary_values(self) -> "SymptomInput":
        bad = [k for k, v in self.symptoms.items() if v not in (0, 1)]
        if bad:
            raise ValueError(
                f"Symptom values must be 0 or 1. Invalid: {bad}"
            )
        return self


def validate_input(symptoms: dict[str, int], age: int | None = None) -> dict:
    """
    Run input guardrail. Returns a dict with:
      - 'valid': bool
      - 'error': str | None
      - 'emergency': bool  (True = stop pipeline, call emergency services)
      - 'emergency_reason': str | None
    """
    # Pydantic validation
    try:
        SymptomInput(symptoms=symptoms, age=age)
    except Exception as e:
        return {"valid": False, "error": str(e), "emergency": False, "emergency_reason": None}

    # Emergency symptom combinations — halt pipeline immediately
    s = symptoms
    emergency_reason = None

    if s.get("chest_pain") and s.get("shortness_of_breath"):
        emergency_reason = "Chest pain + shortness of breath — possible cardiac or pulmonary emergency."
    elif s.get("loss_of_consciousness"):
        emergency_reason = "Loss of consciousness reported — immediate emergency care required."
    elif s.get("difficulty_breathing") and s.get("high_fever"):
        emergency_reason = "Difficulty breathing with high fever — possible severe respiratory illness."
    elif s.get("sudden_severe_headache") and s.get("stiff_neck"):
        emergency_reason = "Sudden severe headache + stiff neck — possible meningitis."

    if emergency_reason:
        return {
            "valid": False,
            "error": emergency_reason,
            "emergency": True,
            "emergency_reason": emergency_reason,
        }

    return {"valid": True, "error": None, "emergency": False, "emergency_reason": None}


# ---------------------------------------------------------------------------
# Output guardrail — checks the model's predictions before showing to user
# ---------------------------------------------------------------------------

def validate_output(prediction: dict, age: int | None = None) -> dict:
    """
    Run output guardrail on model prediction. Returns a dict with:
      - 'safe': bool
      - 'risk_level': 'low' | 'moderate' | 'high' | 'critical'
      - 'escalate': bool  (True = must be reviewed by a doctor)
      - 'flags': list[str]  (reasons for escalation)
      - 'report_suffix': str  (always contains the disclaimer)
    """
    flags   = []
    escalate = False

    primary   = prediction.get("primary_diagnosis", "").lower()
    confidence = prediction.get("confidence", 1.0)

    # Low confidence
    if confidence < 0.40:
        flags.append(f"Low confidence ({confidence:.0%}) — prediction is uncertain.")
        escalate = True

    # High-risk disease
    if any(h in primary for h in HIGH_RISK_DISEASES):
        flags.append(f"'{primary}' is a high-risk diagnosis requiring immediate medical attention.")
        escalate = True

    # Elderly patient
    if age is not None and age >= 70:
        flags.append("Patient age ≥ 70 — elevated risk, clinician review recommended.")
        escalate = True

    # Determine overall risk level
    if not flags:
        risk_level = "low"
    elif escalate and any(h in primary for h in HIGH_RISK_DISEASES):
        risk_level = "critical"
    elif escalate:
        risk_level = "high"
    else:
        risk_level = "moderate"

    return {
        "safe":          not escalate,
        "risk_level":    risk_level,
        "escalate":      escalate,
        "flags":         flags,
        "report_suffix": DISCLAIMER,
    }
